### ISSUE TITLE
Problems compiling on FreeBSD

### ISSUE THREAD

**Issue by smnbldwn** [StavromulaBeta/ersatz#1]
I tried to compile this project on FreeBSD using the command line and following the instructions in the ReadMe. I had already installed the required libraries but got errors when I used the make command. I then tried with debugging flags and got the following:

`$ make -d e
cc ersatz.c -o ersatz `sdl2-config --libs --cflags` `curl-config --libs --cflags` `xml2-config --libs --cflags` -l:libSDL2_ttf.so -l:libSDL2_image.so -Ofast -flto -s
ld: error: undefined symbol: backtrace
>>> referenced by ld-temp.o
>>>               lto.tmp:(throw_error)

ld: error: undefined symbol: backtrace_symbols_fd
>>> referenced by ld-temp.o
>>>               lto.tmp:(throw_error)
cc: error: linker command failed with exit code 1 (use -v to see invocation)

*** Failed target:  optimised
*** Failed command: cc ersatz.c -o ersatz `sdl2-config --libs --cflags` `curl-config --libs --cflags` `xml2-config --libs --cflags` -l:libSDL2_ttf.so -l:libSDL2_image.so -Ofast -flto -s
*** Error code 1

Stop.
make: stopped in /usr/home/simon/Downloads/project`

Do you have any suggestions to get this code to compile? I would like to demo it on open evening in a week's time.

**Comment by smnbldwn** [comment]
Having done some research on this, it turns out I should be using gmake in freebsd instead of make as gmake the Linux/GNU make. Unfortunately with gmake, I still get errors, probably because the libraries are in different places and called from C differently. I will keep on trying with this...

`$ gmake
cc ersatz.c -o ersatz `sdl2-config --libs --cflags` `curl-config --libs --cflags` `xml2-config --libs --cflags` -l:libSDL2_ttf.so -l:libSDL2_image.so -Ofast -flto -s
ld: error: undefined symbol: backtrace
>>> referenced by ld-temp.o
>>>               lto.tmp:(throw_error)

ld: error: undefined symbol: backtrace_symbols_fd
>>> referenced by ld-temp.o
>>>               lto.tmp:(throw_error)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
gmake: *** [Makefile:6: optimised] Error 1
`

**Comment by StavromulaBeta** [comment]
Hmmm perhaps try `-lunwind` to link against libunwind? I've never really used BSD properly so I probably won't be much help

**Comment by smnbldwn** [comment]
I think the next step is a Debian install, just to get this working!

**Comment by smnbldwn** [comment]
I got it working on my Kali box! Kali is a Debian-based rolling distro so all the libraries were up to date.

**Comment by StavromulaBeta** [comment]
ah yeah that'd make sense - nice!
